development:
  adapter: postgresql
  encoding: unicode
  database: appointime_development
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appointime_test
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: appointime_production
  password:

